name = "EAO"
uuid = "afd41b75-4863-4e42-bc7f-f9b16f2b413f"
authors = ["Luis van Sandbergen <luis.vansandbergen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
